### ISSUE TITLE
Throw when regex is not global

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/super-regex#5]
https://github.com/sindresorhus/super-regex/blob/690235582ec311c062c429f282d83705b5f0de6c/readme.md?plain=1#L47

What if we threw an error as well? This way, we could reduce the amount of future support requests unknowing of this message.

**Comment by sindresorhus** [comment]
That already happens, but maybe we should customize the error for `super-regex` and maybe even recommend using `.firstMatch` instead then.
